### ISSUE TITLE
Good work !!! 

### ISSUE THREAD

**Issue by PanGao-1** [rubbish001/Co-Fix3d#6]
I believe your work will establish a new benchmark for the nuScenes dataset, achieving recognition comparable to BEVFusion.  And I am sincerely grateful for your disclosure of the four-step training methodology, as my prolonged attempts to freeze the backbone have yielded no good results.

Then I will endeavor to implement your approach, and multi-step training indeed facilitates the development of innovative methods. 

Please continue your excellent work!  I believe that it will soon be accepted in a premier conference.

**Comment by WenxuanLi-whu** [comment]
Thank you.
