### ISSUE TITLE
GPU数量、Batch_size 大小 以及 学习率之间的关系

### ISSUE THREAD

**Issue by ALLLLLecy** [rubbish001/Co-Fix3d#7]
大佬，我能否问一下，如果原始论文的配置是这样的：
GPU 数量：8
批次大小：2
学习率：0.003
而我现在电脑的配置仅有2个GPU，那么我在复现论文的时候如果按照原始论文的批次大小不变的情况下，学习率是分按照GPU数量进行等比例缩放？即：
GPU 数量：2
批次大小：2
学习率：0.00075
我在复现 SAFDNet 论文的时候遇到了这个问题，使用论文相同的配置得到的精度很低

**Comment by WenxuanLi-whu** [comment]
这个很玄学，训练轮数一样，学习率一样，我试过2,3,4个gpu，影响只有0.1%左右。8卡的没有资源训练，我也不清。我感觉他们可能跟我们一样用相同的配置文件训练了一个权重，然后用很小的学习率继续训了好多轮，选择最好的那个权重作为最后的结论，有资源是可以这样搞的。多轮训练可能偏离0.3%以上。我感觉你直接采用他的学习率，直接训练，可能跟他的差不多吧

**Comment by ALLLLLecy** [comment]
也就是说，用2卡训练配置和原始论文一样的话，影响只有0.1%左右？

**Comment by WenxuanLi-whu** [comment]
我这边测试是这样的，如果他们的权重初始化跟公布的不一样，或者有其他trick都会影响的

**Comment by ALLLLLecy** [comment]
好的，感谢你的回复，期待能够早日看到你的工作被录用，祝科研顺利。
